export const GET_MEME_LINKS = "GET_MEME_LINKS"
export const GET_MEME_THUMBNAIL_LINKS = "GET_MEME_THUMBNAIL_LINKS"
export const INCREASE_PAGE_COUNTER = "INCREASE_PAGE_COUNTER"
export const DECREASE_PAGE_COUNTER = "DECREASE_PAGE_COUNTER"
